"""
ZeyLang — Programming Language for AI, Robot, Space
Compiler, ZeyLang -> C. @ namespace calls, robot/space libraries, AI
integration (curl via fork/exec, no libcurl), list/string indexing,
len/error builtins. v3.0 adds: C_IO_RUNTIME (argv/read_file/write_file/
run_command — always included, needs only stdio.h) so a *compiled*
ZeyLang program can act as a real CLI compiler itself (read a source
file, write generated C, shell out to gcc) — the crux of self-hosting
without Python. main() now takes (argc, argv).

BUG FIX (found via v3.0 self-compilation): top-level ("global")
variables were only ever declared as locals inside main(), so any
function referencing a top-level variable (not passed as a parameter —
e.g. a constant built once at module level) produced C referencing an
undeclared identifier. Fixed: top-level variables are now real C
file-scope globals (zero-initialized, since C requires file-scope
initializers to be compile-time constants and zey_none() is a function
call — zero-init already equals zey_none() since ZEY_NONE is enum 0).

SECURITY NOTE on the AI API key: never hardcoded. Default from
ZEY_AI_API_KEY env var; override at runtime with ai@config(key="...").
"""

import os
import subprocess
import sys

from lexer import Lexer, LexerError
from parser import (
    Parser, ParserError,
    Assign, Return, Break, Continue, Pass, ExprStmt, If, While, For, FuncDef,
    Literal, Identifier, ListLiteral, BinOp, UnaryOp, Attribute, Call, Index,
)


class CompileError(Exception):
    def __init__(self, message):
        super().__init__(f"[Compiler] {message}")


def _c_string_literal(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 32:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _collect_locals(statements, exclude):
    names, seen = [], set(exclude)

    def visit(stmt):
        if isinstance(stmt, Assign):
            if stmt.name not in seen:
                seen.add(stmt.name)
                names.append(stmt.name)
        elif isinstance(stmt, For):
            if stmt.var_name not in seen:
                seen.add(stmt.var_name)
                names.append(stmt.var_name)
            for s in stmt.body:
                visit(s)
        elif isinstance(stmt, If):
            for _, body in stmt.branches:
                for s in body:
                    visit(s)
            if stmt.else_body:
                for s in stmt.else_body:
                    visit(s)
        elif isinstance(stmt, While):
            for s in stmt.body:
                visit(s)
        elif isinstance(stmt, FuncDef):
            raise CompileError(f"nested function '{stmt.name}' is not supported — top-level functions only")

    for s in statements:
        visit(s)
    return names


C_RUNTIME = r"""// ==== ZeyLang runtime — generated by zeylang_compiler.py ====
// Requires GCC (statement-expression extension). Build: gcc -o program program.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

typedef enum { ZEY_NONE, ZEY_BOOL, ZEY_NUM, ZEY_STR, ZEY_LIST } ZeyTag;
typedef struct ZeyValue ZeyValue;
typedef struct ZeyList { ZeyValue *items; int count; int capacity; } ZeyList;
struct ZeyValue { ZeyTag tag; union { int b; double n; const char *s; ZeyList *list; } as; };

static ZeyValue zey_none(void) { ZeyValue v; v.tag = ZEY_NONE; return v; }
static ZeyValue zey_bool(int b) { ZeyValue v; v.tag = ZEY_BOOL; v.as.b = b; return v; }
static ZeyValue zey_num(double n) { ZeyValue v; v.tag = ZEY_NUM; v.as.n = n; return v; }
static ZeyValue zey_str(const char *s) { ZeyValue v; v.tag = ZEY_STR; v.as.s = s; return v; }

static ZeyValue zey_list_new(void) {
    ZeyValue v; v.tag = ZEY_LIST;
    v.as.list = (ZeyList*)malloc(sizeof(ZeyList));
    v.as.list->items = NULL; v.as.list->count = 0; v.as.list->capacity = 0;
    return v;
}
static void zey_list_push(ZeyValue listval, ZeyValue item) {
    ZeyList *l = listval.as.list;
    if (l->count >= l->capacity) {
        l->capacity = l->capacity ? l->capacity * 2 : 4;
        l->items = (ZeyValue*)realloc(l->items, sizeof(ZeyValue) * l->capacity);
    }
    l->items[l->count++] = item;
}
static void zey_error(const char *msg) { fprintf(stderr, "[Runtime] %s\n", msg); exit(1); }

static ZeyValue zey_index(ZeyValue obj, ZeyValue index) {
    if (index.tag != ZEY_NUM) zey_error("index must be a number");
    int i = (int)index.as.n;
    if (obj.tag == ZEY_LIST) {
        if (i < 0) i += obj.as.list->count;
        if (i < 0 || i >= obj.as.list->count) zey_error("list index out of range");
        return obj.as.list->items[i];
    }
    if (obj.tag == ZEY_STR) {
        int sl = (int)strlen(obj.as.s);
        if (i < 0) i += sl;
        if (i < 0 || i >= sl) zey_error("string index out of range");
        char *b = (char*)malloc(2); b[0] = obj.as.s[i]; b[1] = '\0';
        return zey_str(b);
    }
    zey_error("value is not subscriptable"); return zey_none();
}
static ZeyValue zey_len(ZeyValue v) {
    if (v.tag == ZEY_STR) return zey_num((double)strlen(v.as.s));
    if (v.tag == ZEY_LIST) return zey_num((double)v.as.list->count);
    zey_error("len() expects a string or list"); return zey_none();
}
static ZeyValue zey_error_builtin(ZeyValue v) {
    if (v.tag == ZEY_STR) zey_error(v.as.s);
    zey_error("error() expects a string"); return zey_none();
}
static int zey_truthy(ZeyValue v) {
    switch (v.tag) {
        case ZEY_NONE: return 0;
        case ZEY_BOOL: return v.as.b;
        case ZEY_NUM:  return v.as.n != 0;
        case ZEY_STR:  return v.as.s[0] != '\0';
        case ZEY_LIST: return v.as.list->count > 0;
    }
    return 0;
}
static void zey_print_value(ZeyValue v) {
    switch (v.tag) {
        case ZEY_NONE: printf("None"); break;
        case ZEY_BOOL: printf(v.as.b ? "True" : "False"); break;
        case ZEY_NUM:
            if (v.as.n == (long long)v.as.n) printf("%lld", (long long)v.as.n);
            else printf("%g", v.as.n);
            break;
        case ZEY_STR: printf("%s", v.as.s); break;
        case ZEY_LIST:
            printf("[");
            for (int i = 0; i < v.as.list->count; i++) {
                if (i > 0) printf(", ");
                zey_print_value(v.as.list->items[i]);
            }
            printf("]");
            break;
    }
}
static ZeyValue zey_print(ZeyValue v) { zey_print_value(v); printf("\n"); return zey_none(); }
static ZeyValue zey_ai_chat(ZeyValue message) {
    printf("[ai@chat] "); zey_print_value(message); printf("\n"); return message;
}
static ZeyValue zey_robot_walk(ZeyValue steps) {
    printf("[robot@walk] walking "); zey_print_value(steps); printf(" step(s)\n"); return steps;
}
static ZeyValue zey_robot_arm(ZeyValue servo, ZeyValue angle) {
    printf("[robot@arm] servo "); zey_print_value(servo); printf(" -> "); zey_print_value(angle);
    printf("\xc2\xb0\n"); return angle;
}
static ZeyValue zey_robot_grip(ZeyValue state) {
    if (state.tag != ZEY_STR || (strcmp(state.as.s, "open") != 0 && strcmp(state.as.s, "close") != 0))
        zey_error("robot@grip(...) expects \"open\" or \"close\"");
    printf("[robot@grip] gripper -> %s\n", state.as.s); return state;
}
static ZeyValue zey_robot_sensor(ZeyValue kind) {
    if (kind.tag != ZEY_STR) zey_error("robot@sensor(...) expects a string");
    double r = (double)rand() / (double)RAND_MAX;
    if (strcmp(kind.as.s, "temp") == 0) return zey_num(20.0 + r * 10.0);
    if (strcmp(kind.as.s, "dist") == 0) return zey_num(5.0 + r * 195.0);
    if (strcmp(kind.as.s, "gyro") == 0) {
        ZeyValue list = zey_list_new();
        for (int i = 0; i < 3; i++) zey_list_push(list, zey_num(-5.0 + ((double)rand()/(double)RAND_MAX)*10.0));
        return list;
    }
    zey_error("robot@sensor(...): unknown sensor type"); return zey_none();
}
static ZeyValue zey_robot_speak(ZeyValue text) {
    printf("[robot@speak] "); zey_print_value(text); printf("\n"); return text;
}
static ZeyValue zey_space_orbit(ZeyValue altitude, ZeyValue unit) {
    printf("[space@orbit] orbiting at "); zey_print_value(altitude); zey_print_value(unit); printf("\n");
    return altitude;
}
static ZeyValue zey_space_launch(ZeyValue payload, ZeyValue target) {
    printf("[space@launch] "); zey_print_value(payload); printf(" -> "); zey_print_value(target); printf("\n");
    return payload;
}
static ZeyValue zey_space_thrust(ZeyValue percent) {
    if (percent.tag != ZEY_NUM || percent.as.n < 0 || percent.as.n > 100) zey_error("space@thrust(...) expects 0-100");
    printf("[space@thrust] engine -> "); zey_print_value(percent); printf("%%\n"); return percent;
}
static ZeyValue zey_space_navigate(ZeyValue x, ZeyValue y, ZeyValue z) {
    printf("[space@navigate] heading to ("); zey_print_value(x); printf(", "); zey_print_value(y);
    printf(", "); zey_print_value(z); printf(")\n");
    ZeyValue list = zey_list_new();
    zey_list_push(list, x); zey_list_push(list, y); zey_list_push(list, z);
    return list;
}
static ZeyValue zey_space_telemetry(void) {
    ZeyValue result = zey_list_new();
    zey_list_push(result, zey_num(20000.0 + ((double)rand()/(double)RAND_MAX)*8000.0));
    zey_list_push(result, zey_num(300.0 + ((double)rand()/(double)RAND_MAX)*150.0));
    zey_list_push(result, zey_num(10.0 + ((double)rand()/(double)RAND_MAX)*85.0));
    zey_list_push(result, zey_num(-20.0 + ((double)rand()/(double)RAND_MAX)*80.0));
    ZeyValue pos = zey_list_new();
    for (int i = 0; i < 3; i++) zey_list_push(pos, zey_num(-1000.0 + ((double)rand()/(double)RAND_MAX)*2000.0));
    zey_list_push(result, pos);
    return result;
}
static ZeyValue zey_space_touchdown(ZeyValue coord) {
    printf("[space@touchdown] touchdown at "); zey_print_value(coord); printf("\n"); return coord;
}
static ZeyValue zey_add(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_num(a.as.n + b.as.n);
    if (a.tag == ZEY_STR && b.tag == ZEY_STR) {
        size_t len = strlen(a.as.s) + strlen(b.as.s) + 1;
        char *buf = (char*)malloc(len); snprintf(buf, len, "%s%s", a.as.s, b.as.s);
        return zey_str(buf);
    }
    if (a.tag == ZEY_LIST && b.tag == ZEY_LIST) {
        ZeyValue result = zey_list_new();
        for (int i = 0; i < a.as.list->count; i++) zey_list_push(result, a.as.list->items[i]);
        for (int i = 0; i < b.as.list->count; i++) zey_list_push(result, b.as.list->items[i]);
        return result;
    }
    zey_error("unsupported operand types for +"); return zey_none();
}
static ZeyValue zey_sub(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_num(a.as.n - b.as.n);
    zey_error("unsupported operand types for -"); return zey_none();
}
static ZeyValue zey_mul(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_num(a.as.n * b.as.n);
    zey_error("unsupported operand types for *"); return zey_none();
}
static ZeyValue zey_div(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) {
        if (b.as.n == 0) zey_error("division by zero");
        return zey_num(a.as.n / b.as.n);
    }
    zey_error("unsupported operand types for /"); return zey_none();
}
static ZeyValue zey_mod(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) {
        long long bi = (long long)b.as.n;
        if (bi == 0) zey_error("modulo by zero");
        return zey_num((double)((long long)a.as.n % bi));
    }
    zey_error("unsupported operand types for %%"); return zey_none();
}
static ZeyValue zey_lt(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_bool(a.as.n < b.as.n);
    if (a.tag == ZEY_STR && b.tag == ZEY_STR) return zey_bool(strcmp(a.as.s, b.as.s) < 0);
    zey_error("unsupported operand types for <"); return zey_none();
}
static ZeyValue zey_gt(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_bool(a.as.n > b.as.n);
    if (a.tag == ZEY_STR && b.tag == ZEY_STR) return zey_bool(strcmp(a.as.s, b.as.s) > 0);
    zey_error("unsupported operand types for >"); return zey_none();
}
static ZeyValue zey_le(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_bool(a.as.n <= b.as.n);
    if (a.tag == ZEY_STR && b.tag == ZEY_STR) return zey_bool(strcmp(a.as.s, b.as.s) <= 0);
    zey_error("unsupported operand types for <="); return zey_none();
}
static ZeyValue zey_ge(ZeyValue a, ZeyValue b) {
    if (a.tag == ZEY_NUM && b.tag == ZEY_NUM) return zey_bool(a.as.n >= b.as.n);
    if (a.tag == ZEY_STR && b.tag == ZEY_STR) return zey_bool(strcmp(a.as.s, b.as.s) >= 0);
    zey_error("unsupported operand types for >="); return zey_none();
}
static int zey_values_equal(ZeyValue a, ZeyValue b) {
    if (a.tag != b.tag) return 0;
    switch (a.tag) {
        case ZEY_NONE: return 1;
        case ZEY_BOOL: return a.as.b == b.as.b;
        case ZEY_NUM:  return a.as.n == b.as.n;
        case ZEY_STR:  return strcmp(a.as.s, b.as.s) == 0;
        case ZEY_LIST: {
            if (a.as.list->count != b.as.list->count) return 0;
            for (int i = 0; i < a.as.list->count; i++)
                if (!zey_values_equal(a.as.list->items[i], b.as.list->items[i])) return 0;
            return 1;
        }
    }
    return 0;
}
static ZeyValue zey_eq(ZeyValue a, ZeyValue b) { return zey_bool(zey_values_equal(a, b)); }
static ZeyValue zey_neq(ZeyValue a, ZeyValue b) { return zey_bool(!zey_values_equal(a, b)); }
static ZeyValue zey_neg(ZeyValue a) {
    if (a.tag == ZEY_NUM) return zey_num(-a.as.n);
    zey_error("unsupported operand type for unary -"); return zey_none();
}
static ZeyValue zey_not(ZeyValue a) { return zey_bool(!zey_truthy(a)); }
#define ZEY_AND(a_expr, b_expr) ({ ZeyValue _zt = (a_expr); zey_truthy(_zt) ? (b_expr) : _zt; })
#define ZEY_OR(a_expr, b_expr)  ({ ZeyValue _zt = (a_expr); zey_truthy(_zt) ? _zt : (b_expr); })
// ==== end runtime — compiled program follows ===="""


C_IO_RUNTIME = r"""
#include <sys/wait.h>
static int g_argc = 0;
static char **g_argv = NULL;
static ZeyValue zey_argv(ZeyValue idx) {
    if (idx.tag != ZEY_NUM) zey_error("argv(...) expects a number");
    int i = (int)idx.as.n;
    if (i < 0 || i >= g_argc) return zey_str("");
    return zey_str(g_argv[i]);
}
static ZeyValue zey_read_file(ZeyValue path) {
    if (path.tag != ZEY_STR) zey_error("read_file(...) expects a string path");
    FILE *f = fopen(path.as.s, "rb");
    if (!f) zey_error("read_file: could not open file");
    fseek(f, 0, SEEK_END); long size = ftell(f); fseek(f, 0, SEEK_SET);
    char *buf = (char*)malloc((size_t)size + 1);
    size_t n = fread(buf, 1, (size_t)size, f);
    buf[n] = '\0'; fclose(f);
    return zey_str(buf);
}
static ZeyValue zey_write_file(ZeyValue path, ZeyValue content) {
    if (path.tag != ZEY_STR || content.tag != ZEY_STR) zey_error("write_file(...) expects two strings");
    FILE *f = fopen(path.as.s, "wb");
    if (!f) zey_error("write_file: could not open file for writing");
    fwrite(content.as.s, 1, strlen(content.as.s), f); fclose(f);
    return zey_none();
}
static ZeyValue zey_run_command(ZeyValue cmd) {
    if (cmd.tag != ZEY_STR) zey_error("run_command(...) expects a string");
    int status = system(cmd.as.s);
    if (status == -1) zey_error("run_command: failed to execute");
    return zey_num((double)WEXITSTATUS(status));
}
"""

C_AI_RUNTIME = r"""// ==== ZeyLang AI runtime — ai@prompt shells out to `curl` (fork/exec/pipe) ====
#include <unistd.h>
#include <sys/wait.h>
static const char *zey_ai_endpoint = "https://zey-ai.vercel.app/api/chat";
static char zey_ai_api_key[512] = "";
static char zey_ai_model[256] = "llama-3.3-70b-versatile";
static char *zey_ai_system_prompt = NULL;
static double zey_ai_temperature = 0.7;
static int zey_ai_max_tokens = 1024;
static void zey_ai_init(void) {
    const char *k = getenv("ZEY_AI_API_KEY");
    if (k) { strncpy(zey_ai_api_key, k, sizeof(zey_ai_api_key)-1); zey_ai_api_key[sizeof(zey_ai_api_key)-1]=0; }
}
static ZeyValue zey_ai_set_model(ZeyValue name) {
    if (name.tag != ZEY_STR) zey_error("ai@model(...) expects a string");
    strncpy(zey_ai_model, name.as.s, sizeof(zey_ai_model)-1); zey_ai_model[sizeof(zey_ai_model)-1]=0;
    return name;
}
static ZeyValue zey_ai_set_system(ZeyValue text) {
    if (text.tag != ZEY_STR) zey_error("ai@system(...) expects a string");
    zey_ai_system_prompt = (char*)text.as.s; return text;
}
static void zey_ai_set_key(ZeyValue v) {
    if (v.tag != ZEY_STR) zey_error("ai@config(key=...) expects a string");
    strncpy(zey_ai_api_key, v.as.s, sizeof(zey_ai_api_key)-1); zey_ai_api_key[sizeof(zey_ai_api_key)-1]=0;
}
static void zey_ai_set_temp(ZeyValue v) {
    if (v.tag != ZEY_NUM) zey_error("ai@config(temp=...) expects a number");
    zey_ai_temperature = v.as.n;
}
static void zey_ai_set_max(ZeyValue v) {
    if (v.tag != ZEY_NUM) zey_error("ai@config(max=...) expects a number");
    zey_ai_max_tokens = (int)v.as.n;
}
static char *zey_json_escape(const char *s) {
    size_t len = strlen(s); char *out = (char*)malloc(len*6+1); size_t j=0;
    for (size_t i=0;i<len;i++){ unsigned char c=(unsigned char)s[i];
        if (c=='"'||c=='\\'){out[j++]='\\';out[j++]=(char)c;}
        else if (c=='\n'){out[j++]='\\';out[j++]='n';}
        else if (c=='\t'){out[j++]='\\';out[j++]='t';}
        else if (c=='\r'){out[j++]='\\';out[j++]='r';}
        else if (c<0x20){ j+=(size_t)snprintf(out+j,7,"\\u%04x",c); }
        else out[j++]=(char)c;
    }
    out[j]=0; return out;
}
static char *zey_extract_ai_text(const char *raw) {
    static const char *keys[] = { "\"content\"", "\"response\"", "\"message\"", "\"text\"" };
    for (int k=0;k<4;k++){
        const char *p = strstr(raw, keys[k]); if (!p) continue;
        p = strchr(p+strlen(keys[k]), ':'); if (!p) continue;
        p++; while (*p==' '||*p=='\t'||*p=='\n') p++;
        if (*p != '"') continue; p++;
        char *out=(char*)malloc(strlen(p)+1); size_t j=0;
        while (*p && *p != '"') {
            if (*p=='\\' && *(p+1)) { p++;
                if (*p=='n') out[j++]='\n'; else if (*p=='t') out[j++]='\t';
                else if (*p=='r') out[j++]='\r'; else out[j++]=*p;
            } else out[j++]=*p;
            p++;
        }
        out[j]=0; return out;
    }
    char *out=(char*)malloc(strlen(raw)+1); strcpy(out,raw); return out;
}
static char *zey_run_curl(char *const argv[], const char *body) {
    int in_pipe[2], out_pipe[2];
    if (pipe(in_pipe)!=0 || pipe(out_pipe)!=0) zey_error("failed to create pipes");
    pid_t pid = fork();
    if (pid < 0) zey_error("fork() failed");
    if (pid == 0) {
        dup2(in_pipe[0], STDIN_FILENO); dup2(out_pipe[1], STDOUT_FILENO);
        close(in_pipe[0]); close(in_pipe[1]); close(out_pipe[0]); close(out_pipe[1]);
        execvp("curl", argv);
        fprintf(stderr, "[Runtime] failed to exec curl\n"); _exit(127);
    }
    close(in_pipe[0]); close(out_pipe[1]);
    size_t body_len = strlen(body), written = 0;
    while (written < body_len) {
        ssize_t n = write(in_pipe[1], body+written, body_len-written);
        if (n <= 0) break; written += (size_t)n;
    }
    close(in_pipe[1]);
    size_t cap=4096, len=0; char *out=(char*)malloc(cap); char chunk[4096]; ssize_t n;
    while ((n = read(out_pipe[0], chunk, sizeof(chunk))) > 0) {
        if (len+(size_t)n+1 > cap) { cap=(len+(size_t)n+1)*2; out=(char*)realloc(out,cap); }
        memcpy(out+len, chunk, (size_t)n); len += (size_t)n;
    }
    out[len]=0; close(out_pipe[0]);
    int status; waitpid(pid, &status, 0);
    return out;
}
static ZeyValue zey_ai_prompt(ZeyValue text) {
    if (text.tag != ZEY_STR) zey_error("ai@prompt(...) expects a string");
   
